#include "cli/options.h"

#include <stdio.h>

void sweetwall_cli_usage(FILE *out) {
	fputs("usage: sweetwall [options]\n"
	      "\n"
	      "options:\n"
	      "      --background COLOR\n"
	      "                     override background: #rrggbb or #rrggbbaa\n"
	      "  -b, --backend BACKEND\n"
	      "                     override backend: sweetbg, awww, or auto\n"
	      "  -c, --columns COLUMNS\n"
	      "                     override maximum grid columns (1..1024)\n"
	      "      --config PATH  load an alternate configuration file\n"
	      "  -d, --directory DIRECTORY\n"
	      "                     override the wallpaper directory\n"
	      "      --height HEIGHT\n"
	      "                     override thumbnail height (1..16384)\n"
	      "      --hook COMMAND replace/append a temporary on-apply hook\n"
	      "  -m, --margin MARGIN\n"
	      "                     override window margin (0..4096)\n"
	      "      --no-config    use built-in defaults without loading "
	      "config\n"
	      "      --no-hooks     disable configured on-apply hooks\n"
	      "  -o, --output NAME select a Wayland output for this run\n"
	      "  -p, --position POSITION\n"
	      "                     override position: center, left, right, "
	      "top, or bottom\n"
	      "      --print-config print the resolved config and exit\n"
	      "      --radius RADIUS\n"
	      "                     override grid corner radius (0..4096)\n"
	      "      --ring COLOR\n"
	      "                     override ring color: #rrggbb or #rrggbbaa\n"
	      "  -r, --rows ROWS\n"
	      "                     override maximum visible rows (1..1024)\n"
	      "  -s, --spacing SPACING\n"
	      "                     override grid spacing (0..4096)\n"
	      "      --spinner COLOR\n"
	      "                     override spinner color: #rrggbb or "
	      "#rrggbbaa\n"
	      "      --tile COLOR\n"
	      "                     override tile color: #rrggbb or #rrggbbaa\n"
	      "  -w, --width WIDTH\n"
	      "                     override thumbnail width (1..16384)\n"
	      "      --preview      enable full-screen live preview\n"
	      "      --no-preview   disable full-screen live preview\n"
	      "  -h, --help         show this help and exit\n"
	      "  -V, --version      show version information and exit\n"
	      "      --clear-cache  remove cached thumbnails and exit\n"
	      "      --diagnose     check the current setup and exit\n",
		out);
}
